[build]
  # Répertoire de publication (optionnel)
  # C'est le répertoire depuis lequel le site sera servi
  publish = "/"

# Configuration de redirection pour les SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# En-têtes personnalisés
[[headers]]
  # Définit les en-têtes pour tous les fichiers dans le répertoire de publication
  for = "/*"
    [headers.values]
    # En-têtes de sécurité recommandés
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    # Cache-Control pour les ressources statiques
    Cache-Control = "public, max-age=31536000"
    
[[headers]]
  # En-têtes spécifiques pour les fichiers HTML
  for = "*.html"
    [headers.values]
    # Ne pas mettre en cache les fichiers HTML pour toujours avoir la dernière version
    Cache-Control = "public, max-age=0, must-revalidate"
